/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package store;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class salesInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form salesInfo
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public salesInfo() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        Connect();
        getTable();
        table1.setRowHeight(30);
    }
    public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/storej", "root", "");
            System.out.println("Database Connect");
        } 
        catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Connection Lost " + ex);
        }
        
    }
    public void getTable(){
        Object [] row;
        try {
            pst = con.prepareStatement("Select * from sales_info");
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)table1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                row = new Object[8];
                row[0] = rs.getInt(1);
                row[1] = rs.getInt(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getString(7);
                row[7] = rs.getString(8);
                model.addRow(row);
                
            }
            
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLbl_date = new javax.swing.JLabel();
        jLbl_price = new javax.swing.JLabel();
        jLbl_ID = new javax.swing.JLabel();
        jLbl_total = new javax.swing.JLabel();
        jLbl_profit = new javax.swing.JLabel();
        jLbl_qty = new javax.swing.JLabel();
        jLbl_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbl_ID1 = new javax.swing.JLabel();
        jBtn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new pjstore.table();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(93, 114, 98));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sales ID :");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALES INFORMATION");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Name :");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity:");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Unit Price :");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total :");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gross Profit:");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date Processed:");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 30));

        jLbl_date.setOpaque(true);
        jPanel8.add(jLbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 130, 30));

        jLbl_price.setOpaque(true);
        jPanel8.add(jLbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, 30));

        jLbl_ID.setOpaque(true);
        jPanel8.add(jLbl_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 30));

        jLbl_total.setOpaque(true);
        jPanel8.add(jLbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 130, 30));

        jLbl_profit.setOpaque(true);
        jPanel8.add(jLbl_profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 130, 30));

        jLbl_qty.setOpaque(true);
        jPanel8.add(jLbl_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 60, 30));

        jLbl_name.setOpaque(true);
        jPanel8.add(jLbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product ID :");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLbl_ID1.setOpaque(true);
        jPanel8.add(jLbl_ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, 30));

        jBtn_delete.setBackground(new java.awt.Color(255, 153, 153));
        jBtn_delete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBtn_delete.setText("DELETE");
        jBtn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_deleteActionPerformed(evt);
            }
        });
        jPanel8.add(jBtn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 260, 570));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sales ID", "ProductID", "Product Name", "Quantity", "Price", "Total", "Net Profit", "Date Processed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 690, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -24, 950, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        
        int selectedRow = table1.getSelectedRow();
        
        
        
        jLbl_ID.setText(model.getValueAt(selectedRow, 0).toString());
        jLbl_ID1.setText(model.getValueAt(selectedRow, 1).toString());
        jLbl_name.setText(model.getValueAt(selectedRow, 2).toString());
        jLbl_qty.setText(model.getValueAt(selectedRow, 3).toString());
        jLbl_price.setText(model.getValueAt(selectedRow, 4).toString());
        jLbl_total.setText(model.getValueAt(selectedRow, 5).toString());
        jLbl_profit.setText(model.getValueAt(selectedRow, 6).toString());
        jLbl_date.setText(model.getValueAt(selectedRow, 7).toString());
        
    }//GEN-LAST:event_table1MouseClicked

    private void jBtn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        
        int response = JOptionPane.showConfirmDialog(null, "Are you sure to delete this product?", "Delete", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
        if(table1.getSelectedRow() <= 0){
            JOptionPane.showMessageDialog(null, "Please Select Product You Want To Delete" , "Delete", JOptionPane.ERROR_MESSAGE);
        }else{
        
        int id = Integer.parseInt(jLbl_ID.getText());
        int id1 = Integer.parseInt(jLbl_ID1.getText());
        int selectedRow = table1.getSelectedRow();
        int qty = Integer.parseInt(model.getValueAt(selectedRow, 3).toString());
        try {
            pst = con.prepareStatement("UPDATE prod_info SET stocks = stocks + ? WHERE prod_ID = '"+id1+"'");
            pst.setInt(1, qty);
            pst.executeUpdate();
            
            pst = con.prepareStatement("DELETE FROM sales_info WHERE sales_id = '"+id+"'");
             pst.execute();
            
        } catch (Exception e) {
        e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Row Deleted");
        getTable();
        }
        }
    }//GEN-LAST:event_jBtn_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbl_ID;
    private javax.swing.JLabel jLbl_ID1;
    private javax.swing.JLabel jLbl_date;
    private javax.swing.JLabel jLbl_name;
    private javax.swing.JLabel jLbl_price;
    private javax.swing.JLabel jLbl_profit;
    private javax.swing.JLabel jLbl_qty;
    private javax.swing.JLabel jLbl_total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private pjstore.table table1;
    // End of variables declaration//GEN-END:variables
}
